// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zvqiuhostvqwxtumrwdp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp2cWl1aG9zdHZxd3h0dW1yd2RwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzAwMzA2NDAsImV4cCI6MjA4NTYwNjY0MH0.CQaSLTSuu7uJPDj840VuMgqg07n7wvO01iehrbKjBMk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});